# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38ca547f4a42d76ea5f02442842e28be38c2e1598d0dec1400cdee1594e72620d19859d0de7ecdbf1a8993d1af34ecab4e4873d75dedec011f25fecf354c109a

test:
  secret_key_base: 4ccce79b29c47d04a07f1ba874aeb41e1965ad5d381ad2f6163688ce9b0a866f6c85e042630ace6830cf9d7c7768bd49ef4481eca25043d58d697ccdff4e9d26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
